networks:
  nocobase:
    driver: bridge

volumes:
  nocobase-storage:
  nocobase-db:

services:
  exp-nocobase-app:
    container_name: exp-nocobase-app
    image: nocobase/nocobase:latest
    restart: always
    networks:
      - nocobase
    depends_on:
      - exp-nocobase-db
    environment:
      # アプリケーションのシークレットキー、ユーザートークンなどを生成するのに使用します
      # APP_KEY が変更されると、古いトークンも無効になります
      # 任意のランダム文字列にし、外部に漏らさないようにしてください
      - APP_KEY=${APP_KEY:-changeme}
      # データベースタイプ、postgres、mysql、mariadb に対応
      - DB_DIALECT=mariadb
      # データベースホスト、既存のデータベースサーバーの IP に置き換えることができます
      - DB_HOST=exp-nocobase-db
      # データベース名
      - DB_DATABASE=nocobase
      # データベースユーザー
      - DB_USER=${DB_USER:-root}
      # データベースパスワード
      - DB_PASSWORD=${DB_PASSWORD:-P@ssw0rd}
      # データベーステーブル名、フィールド名をスネークケーススタイルに変換するかどうか
      - DB_UNDERSCORED=true
      # タイムゾーン
      - TZ=Asia/Tokyo
      # 商用プラグインのためのサービスプラットフォームのユーザー名とパスワード
      - NOCOBASE_PKG_USERNAME=
      - NOCOBASE_PKG_PASSWORD=

    volumes:
      - nocobase-storage:/app/nocobase/storage
    ports:
      - 10004:80
    # init: true

  # 既存のデータベースサービスを使用する場合、mariadb を起動する必要はありません
  exp-nocobase-db:
    container_name: exp-nocobase-db
    image: mariadb:11
    environment:
      MYSQL_DATABASE: nocobase
      MYSQL_USER: ${MYSQL_USER:-nocobase}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-P@ssw0rd}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-P@ssw0rd}
    restart: always
    volumes:
      - nocobase-db:/var/lib/mysql
    networks:
      - nocobase
